name: servplatform
description: A Flutter application for serv platform.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  

   # Utilities
  flutter_launcher_icons: ^0.7.4
  provider_architecture: ^1.0.5
  shared_preferences: ^0.5.6
  connectivity: ^0.4.6+2
  app_settings: ^3.0.0+1
  device_info: ^0.4.1+4
  path_provider: ^1.5.1
  hive_flutter: ^0.3.0+1
  built_value: ^7.0.4
  http_parser: ^3.1.3
  provider: ^4.0.1
  get_it: ^3.1.0
  mime: ^0.9.6+3
  hive: ^1.3.0
  dio: ^3.0.8
  algolia: ^0.1.6+1
  google_maps_place_picker:
  google_maps_flutter:

  # UI Utilities
  flutter_platform_widgets: ^0.30.1
  auto_animated: any
  sliding_up_panel: ^1.0.0
  cached_network_image: any

  # UI Widgets
  flare_splash_screen: any
  cupertino_icons: ^0.1.3
  flare_flutter: any
  flare_loading: any
  charts_flutter: any

  google_map_location_picker:

  # firebase
  cloud_firestore: ^0.12.9
  firebase_core: ^0.4.0+8


dev_dependencies:
  flutter_test:
    sdk: flutter

  built_value_generator: ^7.0.4
  hive_generator: ^0.7.0
  build_runner: ^1.7.2
  pedantic: ^1.8.0
  logger: ^0.8.2
  mockito: ^4.1.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  #plugin:
   # androidPackage: com.limengyun.realrichtext
   # pluginClass: RealRichTextPlugin

  assets:
    - assets/animations/
    - assets/fonts/
    - assets/images/
    - assets/lang/en.json
    - assets/lang/es.json
    - assets/lang/ru.json
    - assets/mapstyle/map_style.txt

  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
